
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 22 15:26:14 BST 2008
//----------------------------------------------------

package de.hu.logic.parser;

/** CUP generated class containing symbol constants. */
public class FOSym {
  /* terminals */
  public static final int LT = 4;
  public static final int FORMULA = 12;
  public static final int FORALL = 30;
  public static final int NEG = 25;
  public static final int RBRACE = 27;
  public static final int LFP = 17;
  public static final int US = 2;
  public static final int LP = 6;
  public static final int RP = 7;
  public static final int SLASH = 9;
  public static final int WEDGE = 23;
  public static final int NAME = 14;
  public static final int LOGIC = 11;
  public static final int LBRACE = 26;
  public static final int GT = 5;
  public static final int GFP = 18;
  public static final int SUB = 28;
  public static final int LCB = 15;
  public static final int STRING = 31;
  public static final int IFP = 19;
  public static final int TYPE = 13;
  public static final int COMMA = 3;
  public static final int EOF = 0;
  public static final int VEE = 24;
  public static final int BOT = 21;
  public static final int TOP = 22;
  public static final int EXISTS = 29;
  public static final int error = 1;
  public static final int DOT = 10;
  public static final int DFP = 20;
  public static final int RCB = 16;
  public static final int EQ = 8;
}

