
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 22 11:22:47 BST 2008
//----------------------------------------------------

package de.hu.logic.parser;

/** CUP generated class containing symbol constants. */
public class FOSym {
  /* terminals */
  public static final int LT = 3;
  public static final int FORMULA = 11;
  public static final int FORALL = 28;
  public static final int NEG = 23;
  public static final int RBRACE = 25;
  public static final int LFP = 14;
  public static final int LP = 5;
  public static final int RP = 6;
  public static final int SLASH = 8;
  public static final int WEDGE = 21;
  public static final int NAME = 13;
  public static final int LOGIC = 10;
  public static final int LBRACE = 24;
  public static final int GT = 4;
  public static final int GFP = 15;
  public static final int SUB = 26;
  public static final int STRING = 29;
  public static final int TYPE = 12;
  public static final int IFP = 16;
  public static final int COMMA = 2;
  public static final int EOF = 0;
  public static final int VEE = 22;
  public static final int BOT = 19;
  public static final int TOP = 20;
  public static final int EXISTS = 27;
  public static final int error = 1;
  public static final int DOT = 9;
  public static final int NU = 18;
  public static final int DFP = 17;
  public static final int EQ = 7;
}

