
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 26 11:57:11 CEST 2007
//----------------------------------------------------

package de.hu.logic.parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int LT = 2;
  public static final int FORMULA = 10;
  public static final int NEG = 19;
  public static final int RBRACE = 21;
  public static final int LP = 4;
  public static final int RP = 5;
  public static final int SLASH = 7;
  public static final int WEDGE = 17;
  public static final int NAME = 12;
  public static final int LOGIC = 9;
  public static final int LBRACE = 20;
  public static final int GT = 3;
  public static final int MU = 13;
  public static final int SUB = 22;
  public static final int STRING = 23;
  public static final int TYPE = 11;
  public static final int EOF = 0;
  public static final int VEE = 18;
  public static final int BOT = 15;
  public static final int TOP = 16;
  public static final int error = 1;
  public static final int DOT = 8;
  public static final int NU = 14;
  public static final int EQ = 6;
}

